services:
  sniffle:
    environment:
      - ${USB_DEVICE}:${USB_DEVICE}
    container_name: sniffle
    hostname: sniffle
    build:
      context: ./sniffle
      dockerfile: Dockerfile
    image: sniffle:latest
    device_cgroup_rules:
      - 'c 189:* rwm'
    tty: true
    devices: 
      - ${USB_DEVICE}:${USB_DEVICE}
    entrypoint: ["python3", "/src/Sniffle/python_cli/sniff_receiver.py", "-s", "${USB_DEVICE}", "-b", "921600", "-l", "-e", "-z", "--zmqsetting", "0.0.0.0:4222", "-v"]

  zmqDecoder:
    container_name: zmqDecoder
    hostname: zmqDecoder
    build:
      context: ./DroneID
      dockerfile: Dockerfile
    image: droneid:latest
    entrypoint: ["python3", "/src/DroneID/zmq_decoder.py", "-z", "--zmqclients", "sniffle:4222", "--zmqsetting", "0.0.0.0:4224", "-v"]

  zmqToTar1090:
    container_name: zmqToTar1090
    build:
      context: ./zmqToTar1090
      dockerfile: Dockerfile
    image: zmqtotar1090:latest
    entrypoint: ["python3", "/src/zmqToTar1090/zmqToTar1090.py", "--zmqsetting", "zmqDecoder:4224", "--zmqsbs", "--sbssetting", "feed-01.ridxchange.com:32006", "-v"]
